// ═══════════════════════════════════════════════════════════════
// runners/ui/uiTestRunner.ts
// ASTRA Framework — UI Test Runner
// Orchestrates: schema load → A* search → codegen → Playwright exec
// ═══════════════════════════════════════════════════════════════

import * as fs       from "fs-extra";
import * as path     from "path";
import { execSync }  from "child_process";
import { ENV }       from "../../utils/envLoader";
import { logger }    from "../../utils/logger";
import { UiCodeGenerator } from "../../codegen/uiCodeGenerator";
import { FieldSchema }     from "../../schemas/fieldSchema.interface";
import { loadUiSchema }    from "../../utils/schemaResolver";
import { reconcileUiSchema } from "../../utils/schemaReconciler";

// ═══════════════════════════════════════════════════════════════
// Interfaces
// ═══════════════════════════════════════════════════════════════
export interface UiRunResult {
  success:       boolean;
  testsGenerated: number;
  testsPassed:   number;
  testsFailed:   number;
  duration:      number;
  reportPath:    string;
}

// ═══════════════════════════════════════════════════════════════
// UiTestRunner
// ═══════════════════════════════════════════════════════════════
export class UiTestRunner {

  private readonly schemaPath: string;
  private readonly reportDir:  string;

  constructor(schemaPath?: string) {
    // Use process.cwd() = project root (where package.json lives)
    // __dirname resolves to compiled/source location and can drift
    const root      = process.cwd();
    this.schemaPath = schemaPath
      ?? path.resolve(root, "schemas/ui/autoGeneratedSchema.json");
    this.reportDir  = path.resolve(root, ENV.TEST_REPORT_DIR);
  }

  // ═══════════════════════════════════════════════════════════
  // run — full pipeline: load → generate → execute
  // ═══════════════════════════════════════════════════════════
  async run(): Promise<UiRunResult> {
    const startTime = Date.now();
    logger.divider("UI Test Runner — Starting");

    // ─── Load schema ─────────────────────────────────────────
    const rawSchema = await this.loadSchema();
    if (!rawSchema) {
      return this.failResult("Schema not found", startTime);
    }

    // ─── Reconcile schema against LIVE page ───────────────────
    // This is the self-healing step:
    // Removes fields not on the real page
    // Adds new fields found on the real page
    // Updates stale selectors/types
    logger.info("🔄 Reconciling schema against live page...");
    const { schema, report } = await reconcileUiSchema(rawSchema);

    if (report.reconciled) {
      logger.info(`  Schema updated: +${report.fieldsAdded.length} added, -${report.fieldsRemoved.length} removed, ~${report.fieldsUpdated.length} updated`);
    } else {
      logger.info("  Schema matches live page perfectly ✅");
    }

    // ─── Generate Playwright test files via codegen ───────────
    logger.info("⚙️  Generating UI test files from A* search...");
    const generator = new UiCodeGenerator(schema);
    const codeGen   = await generator.generate();

    logger.info(`✅ Generated ${codeGen.savedTo.length} test files`);

    // ─── Execute generated tests via Playwright ───────────────
    logger.info("🚀 Executing generated Playwright UI tests...");
    const execResult = this.executeTests(codeGen.savedTo);

    const duration = Date.now() - startTime;

    return {
      success:        execResult.exitCode === 0,
      testsGenerated: codeGen.savedTo.length,
      testsPassed:    execResult.passed,
      testsFailed:    execResult.failed,
      duration,
      reportPath:     path.join(this.reportDir, "index.html"),
    };
  }

  // ═══════════════════════════════════════════════════════════
  // loadSchema — delegates to central schemaResolver
  // Priority: autoGeneratedSchema.json → registrationSchema.ts → default
  // ═══════════════════════════════════════════════════════════
  private async loadSchema(): Promise<FieldSchema | null> {
    try {
      return await loadUiSchema();
    } catch (err) {
      logger.error(`Schema load failed: ${err}`);
      return null;
    }
  }

  // ═══════════════════════════════════════════════════════════
  // executeTests — runs Playwright CLI on generated spec files
  // ═══════════════════════════════════════════════════════════
  private executeTests(
    specFiles: string[]
  ): { exitCode: number; passed: number; failed: number } {
    fs.ensureDirSync(this.reportDir);

    const specPaths = specFiles
      .map((f) => `"${f}"`)
      .join(" ");

    // ─── Playwright CLI flags ─────────────────────────────────
    // --headed   → show browser window (no value needed)
    // (omitted)  → headless mode (default)
    // PWDEBUG=1  → Playwright Inspector (set in env, not as flag)
    const headedFlag = !ENV.HEADLESS ? "--headed" : "";

    const playwrightCmd = [
      "npx playwright test",
      specPaths,
      `--project=${ENV.BROWSER}`,
      `--reporter=html,list`,
      `--output="${this.reportDir}/artifacts"`,
      headedFlag,
    ].filter(Boolean).join(" ");  // filter(Boolean) removes empty strings

    logger.info(`Running: ${playwrightCmd}`);

    try {
      execSync(playwrightCmd, {
        stdio:   "inherit",
        cwd:     path.resolve(process.cwd()),
        env:     {
          ...process.env,          // passes PWDEBUG=1 through if set
          FORCE_COLOR: "1",        // keep coloured output
        },
        timeout: ENV.ASTAR_GOAL_TIMEOUT * 10,
      });

      logger.info("✅ UI tests completed successfully");
      return { exitCode: 0, passed: specFiles.length, failed: 0 };

    } catch (error: any) {
      const exitCode = error.status ?? 1;
      logger.error(`UI tests completed with failures — exit code: ${exitCode}`);
      return { exitCode, passed: 0, failed: specFiles.length };
    }
  }

  // ═══════════════════════════════════════════════════════════
  // failResult — builds failure result object
  // ═══════════════════════════════════════════════════════════
  private failResult(reason: string, startTime: number): UiRunResult {
    logger.error(`UI Runner failed: ${reason}`);
    return {
      success:        false,
      testsGenerated: 0,
      testsPassed:    0,
      testsFailed:    0,
      duration:       Date.now() - startTime,
      reportPath:     "",
    };
  }
}

// ═══════════════════════════════════════════════════════════════
// Direct execution: npm run test:ui
// ═══════════════════════════════════════════════════════════════
async function main(): Promise<void> {
  logger.divider("ASTRA — UI Test Runner");

  const runner = new UiTestRunner();
  const result = await runner.run();

  logger.divider("UI Test Runner — Results");
  logger.info(`  Success        : ${result.success ? "✅ YES" : "❌ NO"}`);
  logger.info(`  Tests Generated: ${result.testsGenerated}`);
  logger.info(`  Tests Passed   : ${result.testsPassed}`);
  logger.info(`  Tests Failed   : ${result.testsFailed}`);
  logger.info(`  Duration       : ${result.duration}ms`);
  logger.info(`  Report         : ${result.reportPath}`);

  process.exit(result.success ? 0 : 1);
}

if (require.main === module) {
  main().catch((err) => {
    logger.error(`UI runner crashed: ${err}`);
    process.exit(1);
  });
}