"""UI/API Delete - Full lifecycle tests (auto-generated by ASTRA)."""
import httpx
import pytest
from playwright.sync_api import Page

BASE_URL = "http://localhost:3000"


@pytest.mark.api
@pytest.mark.e2e
def test_delete_full_lifecycle(api_headers):
    """Full lifecycle: Create user, verify exists, delete, verify gone."""
    # Step 1: Create user
    payload = {
        "firstName": "Lifecycle",
        "lastName": "Test",
        "email": "lifecycle.delete@example.com",
        "password": "Secure@123",
        "username": "lifecycle_del",
        "termsAccepted": True,
    }
    create_resp = httpx.post(f"{BASE_URL}/api/register", json=payload, headers=api_headers)
    assert create_resp.status_code in [200, 201], f"Create failed: {create_resp.text}"
    user_id = create_resp.json().get("id", "123")

    # Step 2: Verify user exists
    get_resp = httpx.get(f"{BASE_URL}/api/register/{user_id}", headers=api_headers)
    assert get_resp.status_code == 200, "User should exist before delete"

    # Step 3: Delete user
    del_resp = httpx.delete(f"{BASE_URL}/api/register/{user_id}", headers=api_headers)
    assert del_resp.status_code in [200, 204], f"Delete failed: {del_resp.text}"

    # Step 4: Verify user is gone
    verify_resp = httpx.get(f"{BASE_URL}/api/register/{user_id}", headers=api_headers)
    assert verify_resp.status_code == 404, "User should not exist after delete"


@pytest.mark.api
@pytest.mark.e2e
def test_delete_bulk_users(api_headers):
    """Create and delete multiple users sequentially."""
    user_ids = []

    for i in range(3):
        payload = {
            "firstName": f"Bulk{i}",
            "lastName": "Delete",
            "email": f"bulk.delete.{i}@example.com",
            "password": "Secure@123",
            "username": f"bulk_del_{i}",
            "termsAccepted": True,
        }
        resp = httpx.post(f"{BASE_URL}/api/register", json=payload, headers=api_headers)
        if resp.status_code in [200, 201]:
            user_ids.append(resp.json().get("id"))

    for uid in user_ids:
        if uid:
            del_resp = httpx.delete(f"{BASE_URL}/api/register/{uid}", headers=api_headers)
            assert del_resp.status_code in [200, 204]


@pytest.mark.ui
@pytest.mark.e2e
def test_delete_full_ui_flow(authenticated_page: Page):
    """UI: Complete delete workflow with confirmation and redirect."""
    page = authenticated_page
    page.goto(f"{BASE_URL}/settings")
    page.wait_for_load_state("networkidle")

    # Navigate to delete section
    delete_link = page.query_selector("a:has-text('Delete'), a:has-text('Account')")
    if delete_link:
        delete_link.click()
        page.wait_for_load_state("networkidle")

    # Find and click delete button
    delete_btn = page.query_selector(
        "button:has-text('Delete Account'), button:has-text('Remove Account'), [data-testid=delete-account]"
    )
    assert delete_btn is not None, "Delete account button should be present"
