"""UI/API Delete - Positive test cases (auto-generated by ASTRA)."""
import httpx
import pytest
from playwright.sync_api import Page

BASE_URL = "http://localhost:3000"


@pytest.mark.api
@pytest.mark.positive
def test_delete_user_returns_success(api_headers):
    """DELETE an existing user returns 200 or 204."""
    # Pre-create a user to delete
    create_payload = {
        "firstName": "Delete",
        "lastName": "Test",
        "email": "delete.test@example.com",
        "password": "Secure@123",
        "username": "delete_test",
        "termsAccepted": True,
    }
    create_resp = httpx.post(f"{BASE_URL}/api/register", json=create_payload, headers=api_headers)
    assert create_resp.status_code in [200, 201], f"Setup failed: {create_resp.text}"
    user_id = create_resp.json().get("id", "123")

    # Delete
    resp = httpx.delete(f"{BASE_URL}/api/register/{user_id}", headers=api_headers)
    assert resp.status_code in [200, 204]


@pytest.mark.api
@pytest.mark.positive
def test_delete_response_has_correct_content_type(api_headers):
    """DELETE response has valid Content-Type when body is returned."""
    user_id = "123"
    resp = httpx.delete(f"{BASE_URL}/api/register/{user_id}", headers=api_headers)
    if resp.status_code == 200:
        assert "application/json" in resp.headers.get("content-type", "")


@pytest.mark.ui
@pytest.mark.positive
def test_delete_account_via_ui(authenticated_page: Page):
    """UI: user can delete their account from settings page."""
    page = authenticated_page
    page.goto(f"{BASE_URL}/settings/account")
    page.wait_for_load_state("networkidle")

    delete_btn = page.query_selector("button:has-text('Delete'), button:has-text('Remove'), [data-testid=delete-account]")
    if delete_btn:
        delete_btn.click()
        # Confirm dialog if present
        confirm = page.query_selector("button:has-text('Confirm'), button:has-text('Yes, delete')")
        if confirm:
            confirm.click()
        page.wait_for_load_state("networkidle")
        assert page.url != f"{BASE_URL}/settings/account"
