"""UI/API Delete - Negative test cases (auto-generated by ASTRA)."""
import httpx
import pytest
from playwright.sync_api import Page

BASE_URL = "http://localhost:3000"


@pytest.mark.api
@pytest.mark.negative
def test_delete_nonexistent_user_returns_404(api_headers):
    """DELETE a user that doesn't exist returns 404."""
    user_id = "999999999"
    resp = httpx.delete(f"{BASE_URL}/api/register/{user_id}", headers=api_headers)
    assert resp.status_code == 404


@pytest.mark.api
@pytest.mark.negative
def test_delete_without_auth_returns_401():
    """DELETE without Authorization header returns 401."""
    user_id = "123"
    resp = httpx.delete(f"{BASE_URL}/api/register/{user_id}")
    assert resp.status_code in [401, 403]


@pytest.mark.api
@pytest.mark.negative
def test_delete_invalid_id_returns_400_or_404(api_headers):
    """DELETE with invalid ID format returns 400 or 404."""
    user_id = "not-a-valid-id!@#"
    resp = httpx.delete(f"{BASE_URL}/api/register/{user_id}", headers=api_headers)
    assert resp.status_code in [400, 404, 422]


@pytest.mark.api
@pytest.mark.negative
def test_delete_already_deleted_user(api_headers):
    """DELETE the same user twice returns 404 on second attempt."""
    user_id = "123"
    httpx.delete(f"{BASE_URL}/api/register/{user_id}", headers=api_headers)
    second_resp = httpx.delete(f"{BASE_URL}/api/register/{user_id}", headers=api_headers)
    assert second_resp.status_code == 404
