// ═══════════════════════════════════════════════════════
// AUTO-GENERATED BY ASTRA FRAMEWORK
// Schema  : ui-registration
// Mode    : NEGATIVE
// Generated: 2026-03-11T08:36:12.744Z
// A* Path : 11 steps | Iterations: 13
// DO NOT EDIT MANUALLY — re-run codegen to regenerate
// ═══════════════════════════════════════════════════════

import { test, expect, Page } from "@playwright/test";

// ─── Test Configuration ────────────────────────────────
const BASE_URL    = process.env.BASE_URL    || "https://techbeamers.com/selenium-webdriver-python-tutorial/";
const LOGIN_URL   = process.env.LOGIN_URL   || "https://techbeamers.com/selenium-webdriver-python-tutorial/";
const TARGET_URL  = process.env.TARGET_PAGE_URL || "https://techbeamers.com/selenium-webdriver-python-tutorial/";
const USERNAME    = process.env.APP_USERNAME || "admin@example.com";
const PASSWORD    = process.env.APP_PASSWORD || "***";

// ─── Test Suite ────────────────────────────────────────
test.describe("ui-registration — NEGATIVE Tests", () => {

  test.beforeEach(async ({ page }) => {
    await loginToApp(page);
    await page.goto(TARGET_URL, { waitUntil: "networkidle" });
    await page.waitForLoadState("domcontentloaded");
  });

  // ─── should show validation errors with invalid field values (A* negative path) ───────────────────────────────────
  test("should show validation errors with invalid field values (A* negative path)", async ({ page }) => {

    // ─── A* Generated Steps [NEGATIVE mode] ─────

    // [personalInfo] email | mandatory=true | f=19.4
    await expect(page.locator("[name=\"email\"], [type=\"email\"], [id=\"email\"]").first()).toBeVisible({ timeout: 5000 });
    await page.locator("[name=\"email\"], [type=\"email\"], [id=\"email\"]").first().clear();
    await page.locator("[name=\"email\"], [type=\"email\"], [id=\"email\"]").first().fill("@nodomain");

    // [personalInfo] lastName | mandatory=true | f=19.4
    await expect(page.locator("[name=\"lastName\"], [id=\"lastName\"], [placeholder*=\"last\" i]").first()).toBeVisible({ timeout: 5000 });
    await page.locator("[name=\"lastName\"], [id=\"lastName\"], [placeholder*=\"last\" i]").first().clear();
    await page.locator("[name=\"lastName\"], [id=\"lastName\"], [placeholder*=\"last\" i]").first().fill("A");

    // [personalInfo] firstName | mandatory=true | f=19.4
    await expect(page.locator("[name=\"firstName\"], [id=\"firstName\"], [placeholder*=\"first\" i]").first()).toBeVisible({ timeout: 5000 });
    await page.locator("[name=\"firstName\"], [id=\"firstName\"], [placeholder*=\"first\" i]").first().clear();
    await page.locator("[name=\"firstName\"], [id=\"firstName\"], [placeholder*=\"first\" i]").first().fill("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");

    // [personalInfo] phone | mandatory=true | f=19.5
    await expect(page.locator("[name=\"phone\"], [type=\"tel\"], [id=\"phone\"]").first()).toBeVisible({ timeout: 5000 });
    await page.locator("[name=\"phone\"], [type=\"tel\"], [id=\"phone\"]").first().clear();
    await page.locator("[name=\"phone\"], [type=\"tel\"], [id=\"phone\"]").first().fill("abcdefghij");

    // [address] addressBlock.street | mandatory=true | f=19.6
    await expect(page.locator("[name=\"street\"], [name=\"address1\"], [id=\"street\"]").first()).toBeVisible({ timeout: 5000 });
    await page.locator("[name=\"street\"], [name=\"address1\"], [id=\"street\"]").first().clear();
    await page.locator("[name=\"street\"], [name=\"address1\"], [id=\"street\"]").first().fill("AA");

    // [address] addressBlock.city | mandatory=true | f=19.6
    await expect(page.locator("[name=\"city\"], [id=\"city\"]").first()).toBeVisible({ timeout: 5000 });
    await page.locator("[name=\"city\"], [id=\"city\"]").first().clear();
    await page.locator("[name=\"city\"], [id=\"city\"]").first().fill("");

    // [address] addressBlock.pincode | mandatory=true | f=19.6
    await expect(page.locator("[name=\"pincode\"], [name=\"zipcode\"], [id=\"pincode\"]").first()).toBeVisible({ timeout: 5000 });
    await page.locator("[name=\"pincode\"], [name=\"zipcode\"], [id=\"pincode\"]").first().clear();
    await page.locator("[name=\"pincode\"], [name=\"zipcode\"], [id=\"pincode\"]").first().fill("abcdef");

    // [address] addressBlock.state | mandatory=true | f=19.6
    await expect(page.locator("select[name=\"state\"], [id=\"state\"]").first()).toBeVisible({ timeout: 5000 });
    await page.locator("select[name=\"state\"], [id=\"state\"]").first().selectOption("");

    // ── Step 2 ──────────────────────────
    await page.waitForSelector('[data-step="1"], .step-1').catch(() => {});

    // [credentials] username | mandatory=true | f=21.4
    await expect(page.locator("[name=\"username\"], [id=\"username\"]").first()).toBeVisible({ timeout: 5000 });
    await page.locator("[name=\"username\"], [id=\"username\"]").first().clear();
    await page.locator("[name=\"username\"], [id=\"username\"]").first().fill("AAAAAAAAAAAAAAAAAAAAA");

    // [credentials] password | mandatory=true | f=21.4
    await expect(page.locator("[name=\"password\"], [id=\"password\"]").first()).toBeVisible({ timeout: 5000 });
    await page.locator("[name=\"password\"], [id=\"password\"]").first().clear();
    await page.locator("[name=\"password\"], [id=\"password\"]").first().fill("password");

    // [credentials] confirmPassword | mandatory=true | f=22.9
    await expect(page.locator("[name=\"confirmPassword\"], [name=\"confirm_password\"]").first()).toBeVisible({ timeout: 5000 });
    await page.locator("[name=\"confirmPassword\"], [name=\"confirm_password\"]").first().clear();
    await page.locator("[name=\"confirmPassword\"], [name=\"confirm_password\"]").first().fill("12345678");

    // ── Submit Form ──────────────────────────────
    const submitBtn = page.locator('button[type="submit"], input[type="submit"], button:has-text("Submit"), button:has-text("Save"), button:has-text("Create")').first();
    await expect(submitBtn).toBeVisible({ timeout: 5000 });
    await submitBtn.click();


    // ── Goal Assertion ──────────────────────────
    // Negative test — expect validation errors, NOT success
    await expect(page.locator('.error, .alert-error, [role="alert"], .invalid-feedback').first())
      .toBeVisible({ timeout: 5000 });

  });

});

// ─── Login Helper ──────────────────────────────────────
async function loginToApp(page: Page): Promise<void> {
  await page.goto(LOGIN_URL, { waitUntil: "networkidle" });

  const usernameSelectors = [
    'input[name="username"]', 'input[name="email"]',
    'input[type="email"]',   'input[id*="user"]',
  ];
  const passwordSelectors = [
    'input[name="password"]', 'input[type="password"]',
  ];
  const submitSelectors = [
    'button[type="submit"]', 'button:has-text("Login")',
    'button:has-text("Sign in")',
  ];

  for (const sel of usernameSelectors) {
    if (await page.locator(sel).isVisible().catch(() => false)) {
      await page.locator(sel).fill(USERNAME);
      break;
    }
  }
  for (const sel of passwordSelectors) {
    if (await page.locator(sel).isVisible().catch(() => false)) {
      await page.locator(sel).fill(PASSWORD);
      break;
    }
  }
  for (const sel of submitSelectors) {
    if (await page.locator(sel).isVisible().catch(() => false)) {
      await page.locator(sel).click();
      break;
    }
  }

  await page.waitForLoadState("networkidle");
}
