"""UI Registration - Positive test cases (auto-generated by ASTRA, pytest-playwright)."""
import pytest
from playwright.sync_api import Page, expect


@pytest.mark.ui
@pytest.mark.positive
def test_registration_form_visible(authenticated_page: Page):
    """All required form fields are visible on the registration page."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    page.wait_for_load_state("networkidle")
    for selector in [
        "[name=firstName], #firstName",
        "[name=lastName], #lastName",
        "[type=email], [name=email]",
        "[type=password], [name=password]",
    ]:
        expect(page.locator(selector).first).to_be_visible()


@pytest.mark.ui
@pytest.mark.positive
def test_registration_valid_submission(authenticated_page: Page):
    """Submitting all valid fields leads to success."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    page.wait_for_load_state("networkidle")

    page.fill("[name=firstName], #firstName", "John")
    page.fill("[name=lastName], #lastName", "Doe")
    page.fill("[type=email], [name=email]", "john.doe@example.com")
    page.fill("[type=password], [name=password]", "Secure@123")

    confirm = page.query_selector("[name=confirmPassword], #confirmPassword")
    if confirm:
        confirm.fill("Secure@123")

    country = page.query_selector("[name=country], #country")
    if country:
        page.select_option("[name=country], #country", index=1)

    terms = page.query_selector("[name=terms], [name=termsAccepted]")
    if terms:
        terms.check()

    page.click("[type=submit], button:has-text('Register'), button:has-text('Submit')")
    page.wait_for_load_state("networkidle")

    assert "success" in page.url or page.query_selector(
        ".success-message, #success, [data-testid=success]"
    ) is not None


@pytest.mark.ui
@pytest.mark.positive
def test_registration_email_field_accepts_valid_email(authenticated_page: Page):
    """Email field accepts a properly formatted address."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    email_locator = page.locator("[type=email], [name=email]").first
    email_locator.fill("valid.user@domain.com")
    assert email_locator.input_value() == "valid.user@domain.com"


@pytest.mark.ui
@pytest.mark.positive
def test_registration_password_min_length_accepted(authenticated_page: Page):
    """Password field accepts a value meeting minimum length requirement."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    pw = page.locator("[type=password], [name=password]").first
    pw.fill("Secure@123")
    assert len(pw.input_value()) >= 8
