"""UI Registration - Negative test cases (auto-generated by ASTRA, pytest-playwright)."""
import pytest
from playwright.sync_api import Page, expect


@pytest.mark.ui
@pytest.mark.negative
def test_registration_submit_empty_form(authenticated_page: Page):
    """Submitting empty form shows validation errors."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    page.wait_for_load_state("networkidle")
    page.click("[type=submit], button:has-text('Register'), button:has-text('Submit')")
    error = page.query_selector(".error, [data-testid=error], [aria-invalid=true], :invalid")
    assert error is not None, "Validation errors should appear on empty submit"


@pytest.mark.ui
@pytest.mark.negative
def test_registration_invalid_email_format(authenticated_page: Page):
    """Invalid email format triggers inline error."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    page.fill("[type=email], [name=email]", "not-an-email")
    page.click("[type=submit], button:has-text('Register')")
    error = page.query_selector(".error, [data-testid=error], [aria-invalid=true]")
    assert error is not None
    assert "success" not in page.url


@pytest.mark.ui
@pytest.mark.negative
def test_registration_password_too_short(authenticated_page: Page):
    """Password shorter than minimum shows validation error."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    page.fill("[type=password], [name=password]", "short")
    page.click("[type=submit], button:has-text('Register')")
    assert "success" not in page.url


@pytest.mark.ui
@pytest.mark.negative
def test_registration_mismatched_passwords(authenticated_page: Page):
    """Mismatched confirm password triggers error."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    page.fill("[type=password], [name=password]", "Secure@123")
    confirm = page.query_selector("[name=confirmPassword], #confirmPassword")
    if confirm:
        confirm.fill("Different@456")
    page.click("[type=submit], button:has-text('Register')")
    assert "success" not in page.url


@pytest.mark.ui
@pytest.mark.negative
def test_registration_sql_injection_in_name(authenticated_page: Page):
    """SQL injection in name field is safely handled."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    page.fill("[name=firstName], #firstName", "'; DROP TABLE users; --")
    page.fill("[type=email], [name=email]", "sql@test.com")
    page.fill("[type=password], [name=password]", "Secure@123")
    page.click("[type=submit], button:has-text('Register')")
    # Should either show error or handle gracefully - not crash
    assert page.query_selector("body") is not None
