"""UI Registration - Full lifecycle tests (auto-generated by ASTRA, pytest-playwright)."""
import pytest
from playwright.sync_api import Page, expect


@pytest.mark.ui
@pytest.mark.e2e
def test_registration_full_flow_a_star_order(authenticated_page: Page):
    """
    Full registration flow in A*-optimised field-fill order:
    email (p=10) → password (p=10) → username (p=10) → firstName (p=9)
    → lastName (p=9) → country (p=8) → terms (p=6) → submit.
    """
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    page.wait_for_load_state("networkidle")

    def fill_if_present(selector: str, value: str) -> None:
        el = page.query_selector(selector)
        if el and el.is_visible():
            el.fill(value)

    def select_if_present(selector: str, index: int = 1) -> None:
        el = page.query_selector(selector)
        if el and el.is_visible():
            page.select_option(selector, index=index)

    def check_if_present(selector: str) -> None:
        el = page.query_selector(selector)
        if el and el.is_visible():
            el.check()

    # A* order: highest priority first
    fill_if_present("[type=email], [name=email]",           "full.test@example.com")
    fill_if_present("[type=password], [name=password]",     "Secure@123")
    fill_if_present("[name=confirmPassword], #confirmPassword", "Secure@123")
    fill_if_present("[name=username], #username",           "full_test_user")
    fill_if_present("[name=firstName], #firstName",         "Full")
    fill_if_present("[name=lastName], #lastName",           "Test")
    select_if_present("[name=country], #country")
    check_if_present("[name=terms], [name=termsAccepted]")

    page.click("[type=submit], button:has-text('Register'), button:has-text('Submit')")
    page.wait_for_load_state("networkidle")

    assert "success" in page.url or page.query_selector(
        ".success-message, #success, [data-testid=success]"
    ) is not None


@pytest.mark.ui
@pytest.mark.e2e
def test_registration_page_title_present(authenticated_page: Page):
    """Registration page has a title or heading."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    title = page.title()
    assert title, "Page should have a title"


@pytest.mark.ui
@pytest.mark.e2e
def test_registration_form_has_submit_button(authenticated_page: Page):
    """Registration page has a visible submit button."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    submit = page.query_selector("[type=submit], button:has-text('Register'), button:has-text('Submit')")
    assert submit is not None, "Submit button must be present"
    assert submit.is_visible(), "Submit button must be visible"


@pytest.mark.ui
@pytest.mark.e2e
def test_registration_tab_order_works(authenticated_page: Page):
    """Tab key navigates through form fields in logical order."""
    page = authenticated_page
    import os
    page.goto(os.getenv("TARGET_PAGE_URL", "/register"))
    page.wait_for_load_state("networkidle")
    first_input = page.query_selector("input:not([type=hidden])")
    if first_input:
        first_input.click()
        page.keyboard.press("Tab")
        # Should move focus to next field without error
        focused = page.evaluate("() => document.activeElement?.tagName")
        assert focused in ["INPUT", "SELECT", "TEXTAREA", "BUTTON"]
