// ═══════════════════════════════════════════════════════════════
// core/schemaBuilder.ts
// ASTRA Framework — Auto Schema Builder
// Converts preflight analyser outputs (DOM + Network) into
// FieldSchema objects — no manual schema writing needed
//Key highlights:
//
// buildSchemasFromPreflight() — single entry point, reads DOM findings + API blueprint from preflight outputs and auto-generates both schemas
// buildUiSchema() — groups DOM fields by section key → builds Section[] with mandatory derived from whether any field in that group has required=true
// buildApiSchema() — prioritises POST endpoints from blueprint, separates flat keys vs nested objects into separate sections automatically
// buildFieldFromDom() — maps every DOM attribute (pattern, minLength, maxLength, options) into typed Field with proper ValidationRule
// buildDataHints() — smart default test data per field type — email gets valid/invalid email samples, phone gets Indian numbers, name gets real names — no manual data needed
// inferFieldType() — reads field key name to infer type — email → email, password → password, phone/mobile → phone
// formatLabel() — converts snake_case / camelCase → Title Case for human-readable labels
// Saves both schemas as autoGeneratedSchema.json in schemas/ui/ and schemas/api/
// ═══════════════════════════════════════════════════════════════

import * as fs   from "fs-extra";
import * as path from "path";
import { ENV }   from "../utils/envLoader";
import { logger } from "../utils/logger";
import {
  FieldSchema,
  FieldType,
  Section,
  Field,
  ChildField,
  GoalCondition,
} from "../schemas/fieldSchema.interface";
import { DomField, DomAnalyserFindings } from "../preflight/domAnalyser";
import { ApiBlueprint }                  from "../preflight/networkInterceptorAnalyser";

// ═══════════════════════════════════════════════════════════════
// Interfaces
// ═══════════════════════════════════════════════════════════════
export interface SchemaBuilderOutput {
  uiSchema:  FieldSchema | null;
  apiSchema: FieldSchema | null;
  savedTo:   { ui: string; api: string };
}

// ═══════════════════════════════════════════════════════════════
// buildSchemasFromPreflight
// Main entry — reads preflight outputs and builds both schemas
// ═══════════════════════════════════════════════════════════════
export async function buildSchemasFromPreflight(): Promise<SchemaBuilderOutput> {
  logger.divider("Schema Builder — Auto-generating schemas from preflight");

  const output: SchemaBuilderOutput = {
    uiSchema:  null,
    apiSchema: null,
    savedTo:   { ui: "", api: "" },
  };

  // ─── Load DOM findings ───────────────────────────────────────
  const domFindings = await loadDomFindings();
  if (domFindings) {
    output.uiSchema = buildUiSchema(domFindings);
    output.savedTo.ui = await saveSchema(output.uiSchema, "ui");
    logger.info(`✅ UI schema built — ${flatFieldCount(output.uiSchema)} fields`);
  } else {
    logger.warn("⚠️  DOM findings not available — UI schema skipped");
  }

  // ─── Load API blueprint ──────────────────────────────────────
  const apiBlueprint = await loadApiBlueprint();
  if (apiBlueprint && apiBlueprint.length > 0) {
    output.apiSchema = buildApiSchema(apiBlueprint);
    output.savedTo.api = await saveSchema(output.apiSchema, "api");
    logger.info(`✅ API schema built — ${apiBlueprint.length} endpoints`);
  } else {
    logger.warn("⚠️  API blueprint not available — API schema skipped");
  }

  return output;
}

// ═══════════════════════════════════════════════════════════════
// buildUiSchema — converts DomAnalyserFindings → FieldSchema
// ═══════════════════════════════════════════════════════════════
function buildUiSchema(domFindings: DomAnalyserFindings): FieldSchema {
  logger.info("Building UI schema from DOM findings...");

  // ─── Group fields by section ─────────────────────────────────
  const sectionMap = new Map<string, DomField[]>();

  for (const field of domFindings.fields) {
    if (!field.visible) continue; // Skip hidden/honeypot fields
    const sectionKey = field.section || "default";
    if (!sectionMap.has(sectionKey)) sectionMap.set(sectionKey, []);
    sectionMap.get(sectionKey)!.push(field);
  }

  // ─── Build sections ──────────────────────────────────────────
  const sections: Section[] = [];
  let sectionIndex = 0;

  for (const [sectionName, fields] of sectionMap.entries()) {
    const hasMandatory = fields.some((f) => f.required);

    const builtFields: Field[] = fields.map((f) =>
      buildFieldFromDom(f)
    );

    sections.push({
      sectionName,
      mandatory:   hasMandatory,
      weight:      hasMandatory ? 10 : 4,
      label:       formatLabel(sectionName),
      fields:      builtFields,
      stepIndex:   fields[0]?.stepIndex ?? sectionIndex,
    });

    sectionIndex++;
  }

  // ─── Goal condition ──────────────────────────────────────────
  const goalCondition: GoalCondition = {
    ui: {
      successSelector: "[data-success], .success-message, .alert-success",
      successText:     "successfully",
      urlContains:     "/success",
    },
  };

  const schema: FieldSchema = {
    schemaId:     "auto-ui-schema",
    version:      "1.0.0",
    target:       "ui",
    description:  `Auto-generated UI schema from ${domFindings.pageTitle}`,
    goalCondition,
    astarConfig: {
      maxIterations:   ENV.ASTAR_MAX_ITERATIONS,
      heuristicWeight: ENV.ASTAR_HEURISTIC_WEIGHT,
      goalTimeout:     ENV.ASTAR_GOAL_TIMEOUT,
    },
    sections,
  };

  logger.info(`UI schema: ${sections.length} sections, multi-step: ${domFindings.isMultiStep}`);
  return schema;
}

// ═══════════════════════════════════════════════════════════════
// buildApiSchema — converts ApiBlueprint[] → FieldSchema
// Takes the first POST endpoint as primary schema target
// ═══════════════════════════════════════════════════════════════
function buildApiSchema(blueprints: ApiBlueprint[]): FieldSchema {
  logger.info("Building API schema from network blueprint...");

  // ─── Prioritise POST endpoints ───────────────────────────────
  const postBlueprints = blueprints.filter((b) => b.method === "POST");
  const primary        = postBlueprints[0] ?? blueprints[0];

  // ─── Build sections from request schema ──────────────────────
  const sections: Section[] = buildApiSections(primary);

  const goalCondition: GoalCondition = {
    api: { successCodes: [200, 201] },
  };

  const schema: FieldSchema = {
    schemaId:    "auto-api-schema",
    version:     "1.0.0",
    target:      "api",
    description: `Auto-generated API schema from ${primary.method} ${primary.path}`,
    baseUrl:     ENV.API_BASE_URL || ENV.BASE_URL,
    endpoint:    primary.path,
    method:      primary.method,
    goalCondition,
    astarConfig: {
      maxIterations:   ENV.ASTAR_MAX_ITERATIONS,
      heuristicWeight: ENV.ASTAR_HEURISTIC_WEIGHT,
      goalTimeout:     ENV.API_TIMEOUT,
    },
    sections,
  };

  logger.info(`API schema: endpoint=${primary.method} ${primary.path}`);
  return schema;
}

// ═══════════════════════════════════════════════════════════════
// buildApiSections — converts request schema into sections
// ═══════════════════════════════════════════════════════════════
function buildApiSections(blueprint: ApiBlueprint): Section[] {
  const sections: Section[] = [];
  const schema = blueprint.requestSchema;

  if (!schema || Object.keys(schema).length === 0) {
    // ─── No schema available — build generic section ──────────
    return [{
      sectionName: "payload",
      mandatory:   true,
      weight:      10,
      fields:      blueprint.requiredFields.map((key, i) => ({
        name:    key,
        type:    "text" as FieldType,
        weight:  10 - i,
        apiKey:  key,
      })),
    }];
  }

  // ─── Group flat keys vs nested objects ───────────────────────
  const flatFields:   Record<string, string> = {};
  const nestedGroups: Record<string, Record<string, string>> = {};

  for (const [key, value] of Object.entries(schema)) {
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      nestedGroups[key] = value as Record<string, string>;
    } else {
      flatFields[key] = value as string;
    }
  }

  // ─── Flat fields → single section ────────────────────────────
  if (Object.keys(flatFields).length > 0) {
    const fields: Field[] = Object.entries(flatFields).map(([key, typeStr]) => ({
      name:    key,
      type:    inferFieldType(key, typeStr),
      weight:  blueprint.requiredFields.includes(key) ? 9 : 4,
      apiKey:  key,
      label:   formatLabel(key),
    }));

    sections.push({
      sectionName: "payload",
      mandatory:   true,
      weight:      10,
      fields,
    });
  }

  // ─── Nested objects → separate sections ──────────────────────
  for (const [groupKey, groupFields] of Object.entries(nestedGroups)) {
    const children: ChildField[] = Object.entries(groupFields).map(([key, typeStr]) => ({
      name:   key,
      type:   inferFieldType(key, typeStr),
      weight: blueprint.requiredFields.includes(key) ? 9 : 4,
      apiKey: key,
      label:  formatLabel(key),
    }));

    const parentField: Field = {
      name:     groupKey,
      type:     "text",
      weight:   8,
      apiKey:   groupKey,
      label:    formatLabel(groupKey),
      children,
    };

    sections.push({
      sectionName: groupKey,
      mandatory:   blueprint.requiredFields.some((f) =>
        children.some((c) => c.name === f)
      ),
      weight: 8,
      fields: [parentField],
    });
  }

  return sections;
}

// ═══════════════════════════════════════════════════════════════
// buildFieldFromDom — converts DomField → Field
// ═══════════════════════════════════════════════════════════════
function buildFieldFromDom(domField: DomField): Field {
  const fieldType = mapDomTypeToFieldType(domField.type, domField.tagName);

  const field: Field = {
    name:        domField.name || domField.id || "unknown",
    type:        fieldType,
    weight:      domField.required ? 9 : 4,
    label:       domField.label || formatLabel(domField.name),
    placeholder: domField.placeholder,
    selector:    domField.selector,
  };

  // ─── Dropdown options ────────────────────────────────────────
  if (domField.options && domField.options.length > 0) {
    field.validValues = domField.options;
  }

  // ─── Validation rules from DOM attributes ────────────────────
  const hasValidation = domField.pattern || domField.minLength || domField.maxLength;
  if (hasValidation) {
    field.validationRule = {
      pattern:   domField.pattern  || undefined,
      minLength: domField.minLength,
      maxLength: domField.maxLength,
    };
  }

  // ─── Data hints based on field type ──────────────────────────
  field.dataHints = buildDataHints(fieldType, domField.name, domField.options);

  return field;
}

// ═══════════════════════════════════════════════════════════════
// buildDataHints — generates sensible test data hints per type
// ═══════════════════════════════════════════════════════════════
function buildDataHints(
  type:    FieldType,
  name:    string,
  options: string[] = []
): Record<string, unknown> {
  const nameLower = name.toLowerCase();

  switch (type) {
    case "email":
      return {
        validSamples:   ["test@example.com", "user@testapp.com"],
        invalidSamples: ["notanemail", "missing@", "@nodomain"],
        format:         "email",
      };
    case "phone":
      return {
        validSamples:   ["9876543210", "8123456789"],
        invalidSamples: ["12345", "abcdefghij"],
        format:         "phone",
        locale:         "en-IN",
      };
    case "password":
      return {
        validSamples:   ["Test@1234", "Secure#Pass9"],
        invalidSamples: ["weak", "12345678", "nouppercaseorspecial"],
      };
    case "date":
      return {
        validSamples:   ["2000-01-01", "1995-06-15"],
        format:         "YYYY-MM-DD",
      };
    case "number":
      return {
        validSamples:   ["100", "250"],
        invalidSamples: ["-1", "abc"],
      };
    case "dropdown":
      return {
        validSamples: options.slice(0, 3),
      };
    case "checkbox":
      return {
        validSamples:   ["true"],
        invalidSamples: ["false"],
      };
    default:
      // Text — check name for hints
      if (/name/i.test(nameLower))    return { validSamples: ["John", "Priya", "Karthick"] };
      if (/city/i.test(nameLower))    return { validSamples: ["Chennai", "Bangalore", "Mumbai"] };
      if (/zip|pin/i.test(nameLower)) return { validSamples: ["600001", "560001"] };
      if (/street/i.test(nameLower))  return { validSamples: ["12 Main Street", "45 Gandhi Road"] };
      return { validSamples: ["TestValue001", "SampleInput"] };
  }
}

// ═══════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════
function mapDomTypeToFieldType(domType: string, tagName: string): FieldType {
  if (tagName === "select")   return "dropdown";
  if (tagName === "textarea") return "textarea";

  const typeMap: Record<string, FieldType> = {
    text:     "text",
    email:    "email",
    password: "password",
    number:   "number",
    tel:      "phone",
    date:     "date",
    checkbox: "checkbox",
    radio:    "radio",
    file:     "file",
    url:      "url",
    search:   "search",
  };

  return typeMap[domType.toLowerCase()] ?? "text";
}

function inferFieldType(key: string, typeStr: string): FieldType {
  const keyLower = key.toLowerCase();
  if (/email/i.test(keyLower))           return "email";
  if (/password|pass/i.test(keyLower))   return "password";
  if (/phone|mobile|tel/i.test(keyLower))return "phone";
  if (/date|dob|birth/i.test(keyLower))  return "date";
  if (typeStr === "number")              return "number";
  if (typeStr === "boolean")             return "checkbox";
  return "text";
}

function formatLabel(name: string): string {
  return name
    .replace(/[_-]/g, " ")
    .replace(/([A-Z])/g, " $1")
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}

function flatFieldCount(schema: FieldSchema): number {
  return schema.sections.reduce((acc, s) =>
    acc + s.fields.reduce((facc, f) =>
      facc + 1 + (f.children?.length ?? 0), 0
    ), 0
  );
}

// ═══════════════════════════════════════════════════════════════
// File I/O
// ═══════════════════════════════════════════════════════════════
async function loadDomFindings(): Promise<DomAnalyserFindings | null> {
  // DOM findings are passed in-memory during same run
  // Fallback: check if saved in reports dir
  const filePath = path.resolve(
    __dirname, "../reports/preflight/domFindings.json"
  );
  if (await fs.pathExists(filePath)) {
    return await fs.readJson(filePath);
  }
  return null;
}

async function loadApiBlueprint(): Promise<ApiBlueprint[] | null> {
  const filePath = path.resolve(
    __dirname, "../payloads/requests/apiBlueprint.json"
  );
  if (await fs.pathExists(filePath)) {
    return await fs.readJson(filePath);
  }
  return null;
}

async function saveSchema(schema: FieldSchema, target: "ui" | "api"): Promise<string> {
  const dir      = path.resolve(__dirname, `../schemas/${target}`);
  await fs.ensureDir(dir);

  const filePath = path.join(dir, "autoGeneratedSchema.json");
  await fs.writeJson(filePath, schema, { spaces: 2 });

  logger.info(`Schema saved → ${filePath}`);
  return filePath;
}