"""ASTRA schema resolver - priority-based schema loader."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from schemas.field_schema import FieldSchema
from utils.logger import logger

_ROOT = Path(__file__).parent.parent
_AUTO_UI = _ROOT / "schemas" / "ui" / "autoGeneratedSchema.json"
_AUTO_API = _ROOT / "schemas" / "api" / "autoGeneratedSchema.json"


def _load_json_schema(path: Path) -> Optional[FieldSchema]:
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return FieldSchema.from_dict(data)
    except Exception as exc:
        logger.warning(f"Failed to parse {path}: {exc}")
        return None


def load_ui_schema() -> FieldSchema:
    """
    Priority:
    1. autoGeneratedSchema.json (from preflight DOM scan)
    2. Manual TypeScript-equivalent Python schema
    """
    schema = _load_json_schema(_AUTO_UI)
    if schema:
        logger.preflight("UI schema loaded from autoGeneratedSchema.json")
        return schema

    from schemas.ui.registration_schema import REGISTRATION_UI_SCHEMA
    logger.preflight("UI schema loaded from manual registration_schema.py")
    return REGISTRATION_UI_SCHEMA


def load_api_schema() -> FieldSchema:
    """
    Priority:
    1. autoGeneratedSchema.json (from preflight network interceptor)
    2. Manual Python schema
    """
    schema = _load_json_schema(_AUTO_API)
    if schema:
        logger.preflight("API schema loaded from autoGeneratedSchema.json")
        return schema

    from schemas.api.registration_schema import REGISTRATION_API_SCHEMA
    logger.preflight("API schema loaded from manual registration_schema.py")
    return REGISTRATION_API_SCHEMA
