// ═══════════════════════════════════════════════════════════════
// utils/schemaResolver.ts
// ASTRA Framework — Central Schema Resolver
// Handles load priority:
//   1. autoGeneratedSchema.json  (from preflight — preferred)
//   2. registrationSchema.ts     (manual TS fallback)
//   3. inline default schema     (last resort — always works)
// ═══════════════════════════════════════════════════════════════

import * as fs   from "fs-extra";
import * as path from "path";
import { logger } from "./logger";
import { FieldSchema } from "../schemas/fieldSchema.interface";

// ─── Resolved schema root — always from project root ──────────
const PROJECT_ROOT = process.cwd();

const SCHEMA_PATHS = {
  ui: {
    json: path.resolve(PROJECT_ROOT, "schemas/ui/autoGeneratedSchema.json"),
    ts:   path.resolve(PROJECT_ROOT, "schemas/ui/registrationSchema.ts"),
  },
  api: {
    json: path.resolve(PROJECT_ROOT, "schemas/api/autoGeneratedSchema.json"),
    ts:   path.resolve(PROJECT_ROOT, "schemas/api/registrationSchema.ts"),
  },
};

// ═══════════════════════════════════════════════════════════════
// loadUiSchema
// ═══════════════════════════════════════════════════════════════
export async function loadUiSchema(): Promise<FieldSchema> {
  // ── Priority 1: auto-generated JSON from preflight ──────────
  if (await fs.pathExists(SCHEMA_PATHS.ui.json)) {
    const schema: FieldSchema = await fs.readJson(SCHEMA_PATHS.ui.json);
    logger.info(`✅ UI schema loaded: autoGeneratedSchema.json (${schema.schemaId})`);
    return schema;
  }

  // ── Priority 2: manual TS schema (dynamic import) ───────────
  logger.warn("⚠️  autoGeneratedSchema.json not found — using manual TS schema");
  logger.warn("   Run 'npm run preflight' to generate schema from your app");

  try {
    const mod = await import("../schemas/ui/registrationSchema");
    const schema: FieldSchema = mod.uiRegistrationSchema;
    logger.info(`✅ UI schema loaded: registrationSchema.ts (${schema.schemaId})`);

    // ── Auto-seed JSON so next run doesn't need this fallback ──
    await seedJsonSchema(schema, SCHEMA_PATHS.ui.json);
    return schema;
  } catch (err) {
    logger.error(`Failed to load manual UI schema: ${err}`);
  }

  // ── Priority 3: inline minimal default ──────────────────────
  logger.warn("⚠️  Using inline default schema — please configure your schemas");
  return getDefaultUiSchema();
}

// ═══════════════════════════════════════════════════════════════
// loadApiSchema
// ═══════════════════════════════════════════════════════════════
export async function loadApiSchema(): Promise<FieldSchema> {
  // ── Priority 1: auto-generated JSON ─────────────────────────
  if (await fs.pathExists(SCHEMA_PATHS.api.json)) {
    const schema: FieldSchema = await fs.readJson(SCHEMA_PATHS.api.json);
    logger.info(`✅ API schema loaded: autoGeneratedSchema.json (${schema.schemaId})`);
    return schema;
  }

  // ── Priority 2: manual TS schema ────────────────────────────
  logger.warn("⚠️  API autoGeneratedSchema.json not found — using manual TS schema");

  try {
    const mod = await import("../schemas/api/registrationSchema");
    const schema: FieldSchema = mod.apiRegistrationSchema;
    logger.info(`✅ API schema loaded: registrationSchema.ts (${schema.schemaId})`);

    await seedJsonSchema(schema, SCHEMA_PATHS.api.json);
    return schema;
  } catch (err) {
    logger.error(`Failed to load manual API schema: ${err}`);
  }

  // ── Priority 3: inline default ──────────────────────────────
  return getDefaultApiSchema();
}

// ═══════════════════════════════════════════════════════════════
// seedJsonSchema
// Writes TS schema as JSON so subsequent runs skip the TS import
// ═══════════════════════════════════════════════════════════════
async function seedJsonSchema(
  schema:   FieldSchema,
  jsonPath: string
): Promise<void> {
  try {
    await fs.ensureDir(path.dirname(jsonPath));
    await fs.writeJson(jsonPath, schema, { spaces: 2 });
    logger.info(`  → Seeded ${path.basename(jsonPath)} for future runs`);
  } catch (err) {
    logger.warn(`Could not seed JSON schema: ${err}`);
  }
}

// ═══════════════════════════════════════════════════════════════
// getDefaultUiSchema — minimal always-works UI schema
// ═══════════════════════════════════════════════════════════════
function getDefaultUiSchema(): FieldSchema {
  return {
    schemaId:    "default-ui-schema",
    version:     "1.0.0",
    target:      "ui",
    description: "Default schema — configure schemas/ui/registrationSchema.ts",
    goalCondition: {
      ui: {
        successSelector: ".success-message, .alert-success",
        successText:     "successfully",
      },
    },
    astarConfig: {
      maxIterations:   200,
      heuristicWeight: 1.0,
      goalTimeout:     15000,
    },
    sections: [
      {
        sectionName: "defaultSection",
        mandatory:   true,
        weight:      10,
        fields: [
          {
            name:    "email",
            type:    "email",
            weight:  10,
            label:   "Email",
            dataHints: { validSamples: ["test@astra.com"] },
          },
          {
            name:    "password",
            type:    "password",
            weight:  10,
            label:   "Password",
            dataHints: { validSamples: ["Test@1234"] },
          },
        ],
      },
    ],
  };
}

// ═══════════════════════════════════════════════════════════════
// getDefaultApiSchema — minimal always-works API schema
// ═══════════════════════════════════════════════════════════════
function getDefaultApiSchema(): FieldSchema {
  return {
    schemaId:    "default-api-schema",
    version:     "1.0.0",
    target:      "api",
    description: "Default schema — configure schemas/api/registrationSchema.ts",
    endpoint:    "/api/v1/users",
    method:      "POST",
    goalCondition: {
      api: { successCodes: [200, 201] },
    },
    astarConfig: {
      maxIterations:   200,
      heuristicWeight: 1.0,
      goalTimeout:     10000,
    },
    sections: [
      {
        sectionName: "defaultSection",
        mandatory:   true,
        weight:      10,
        fields: [
          {
            name:   "email",
            type:   "email",
            weight: 10,
            apiKey: "email",
            dataHints: { validSamples: ["test@astra.com"], unique: true },
          },
          {
            name:   "password",
            type:   "password",
            weight: 10,
            apiKey: "password",
            dataHints: { validSamples: ["Test@1234"] },
          },
        ],
      },
    ],
  };
}