// ═══════════════════════════════════════════════════════════════
// utils/schemaReconciler.ts
// ASTRA Framework — Live Schema Reconciler
//
// THE PROBLEM IT SOLVES:
//   The manual registrationSchema.ts has generic fields
//   (firstName, lastName, email) that don't match YOUR app's
//   actual page fields (campaignName, startDate, budget).
//
//   Even autoGeneratedSchema.json can go stale when devs add
//   or remove fields after the last preflight run.
//
// HOW IT WORKS:
//   1. Load whatever schema exists (auto or manual)
//   2. Do a QUICK live DOM scan of the actual target page
//   3. Compare schema fields vs real page fields
//   4. Remove fields not found on the page
//   5. Add fields found on page but missing from schema
//   6. Save the reconciled schema → A* engine uses correct fields
//
// RESULT: Schema ALWAYS matches the real page — self-healing ✅
// ═══════════════════════════════════════════════════════════════

import * as fs   from "fs-extra";
import * as path from "path";
import { chromium, Browser, Page } from "@playwright/test";
import { ENV }    from "./envLoader";
import { logger } from "./logger";
import {
  FieldSchema,
  FieldType,
  Section,
  Field,
  ResolvedField,
  flattenSchema,
} from "../schemas/fieldSchema.interface";

// ═══════════════════════════════════════════════════════════════
// Interfaces
// ═══════════════════════════════════════════════════════════════

// A field found by live DOM scan
export interface LiveField {
  name:        string;
  id:          string;
  type:        string;       // raw HTML type: "text", "email", etc.
  label:       string;
  placeholder: string;
  required:    boolean;
  selector:    string;
  options:     string[];     // dropdown options
  pattern:     string;
  minLength?:  number;
  maxLength?:  number;
  section:     string;
  stepIndex:   number;
  visible:     boolean;
}

// Summary of what changed during reconciliation
export interface ReconcileReport {
  totalLiveFields:    number;
  totalSchemaFields:  number;
  fieldsAdded:        string[];   // new fields added from page
  fieldsRemoved:      string[];   // old fields removed (not on page)
  fieldsKept:         string[];   // unchanged — matched both sides
  fieldsUpdated:      string[];   // selector/type updated from live scan
  reconciled:         boolean;    // true if any changes were made
  savedTo:            string;     // path of saved reconciled schema
  duration:           number;     // ms taken
}

// ═══════════════════════════════════════════════════════════════
// SchemaReconciler — main class
// ═══════════════════════════════════════════════════════════════
export class SchemaReconciler {

  private readonly schemaType: "ui" | "api";
  private readonly schemaPath: string;

  constructor(schemaType: "ui" | "api" = "ui") {
    this.schemaType = schemaType;
    this.schemaPath = path.resolve(
      process.cwd(),
      `schemas/${schemaType}/autoGeneratedSchema.json`
    );
  }

  // ═════════════════════════════════════════════════════════════
  // reconcile — main entry point
  // Accepts current schema, returns reconciled schema
  // ═════════════════════════════════════════════════════════════
  async reconcile(currentSchema: FieldSchema): Promise<{
    schema: FieldSchema;
    report: ReconcileReport;
  }> {
    const startTime = Date.now();
    logger.divider("Schema Reconciler — Live DOM Sync");

    // ── Step 1: Scan the actual page right now ─────────────────
    logger.info(`🔍 Scanning live page: ${ENV.TARGET_PAGE_URL}`);
    const liveFields = await this.scanLivePage();

    if (liveFields.length === 0) {
      logger.warn("⚠️  No live fields detected — returning current schema unchanged");
      return {
        schema: currentSchema,
        report: this.buildReport([], [], [], [], [], liveFields.length,
          flattenSchema(currentSchema).length, Date.now() - startTime),
      };
    }

    logger.info(`✅ Live scan found ${liveFields.length} fields on page`);

    // ── Step 2: Get all fields from current schema ─────────────
    const schemaFields = flattenSchema(currentSchema);

    logger.info(`📋 Current schema has ${schemaFields.length} fields`);

    // ── Step 3: Compare live vs schema ────────────────────────
    const { added, removed, kept, updated } = this.compareFields(
      liveFields,
      schemaFields
    );

    // Log the diff
    this.logDiff(added, removed, kept, updated);

    // ── Step 4: Build reconciled schema ───────────────────────
    const reconciledSchema = this.buildReconciledSchema(
      currentSchema,
      liveFields,
      schemaFields,
      added,
      removed,
      updated
    );

    // ── Step 5: Save reconciled schema ────────────────────────
    await this.saveReconciledSchema(reconciledSchema);

    const report = this.buildReport(
      added, removed, kept, updated,
      schemaFields.map(f => f.fieldPath),
      liveFields.length,
      schemaFields.length,
      Date.now() - startTime
    );

    logger.info(`✅ Reconciliation complete in ${report.duration}ms`);
    logger.info(`   Added: ${added.length} | Removed: ${removed.length} | Kept: ${kept.length} | Updated: ${updated.length}`);

    return { schema: reconciledSchema, report };
  }

  // ═════════════════════════════════════════════════════════════
  // scanLivePage — quick DOM scan of the actual target page
  // Reuses domAnalyser logic but lightweight (no full analyser)
  // ═════════════════════════════════════════════════════════════
  private async scanLivePage(): Promise<LiveField[]> {
    let browser: Browser | null = null;

    try {
      browser = await chromium.launch({
        headless: ENV.HEADLESS,
        slowMo:   0,          // No slow-mo for reconciler — speed matters
      });

      const page = await browser.newPage();

      // ── Log in first ───────────────────────────────────────
      await this.quickLogin(page);

      // ── Navigate to target page ────────────────────────────
      await page.goto(ENV.TARGET_PAGE_URL, { waitUntil: "networkidle" });
      await page.waitForLoadState("domcontentloaded");

      // ── Wait briefly for dynamic content ──────────────────
      await page.waitForTimeout(1500);

      // ── Trigger lazy-loaded fields ─────────────────────────
      await this.triggerDynamicContent(page);

      // ── Extract all visible fields ─────────────────────────
      const fields = await this.extractFields(page);

      logger.info(`  DOM scan: ${fields.length} visible input fields found`);
      return fields;

    } catch (err) {
      logger.error(`Live DOM scan failed: ${err}`);
      return [];
    } finally {
      if (browser) await browser.close();
    }
  }

  // ═════════════════════════════════════════════════════════════
  // quickLogin — minimal login for reconciler speed
  // ═════════════════════════════════════════════════════════════
  private async quickLogin(page: Page): Promise<void> {
    try {
      await page.goto(ENV.LOGIN_URL, { waitUntil: "networkidle" });

      // Try common username selectors
      const loginSelectors = [
        'input[name="Login"]',
        'input[name="Login"]',
        'input[type="Login"]',
        'input[id*="Login" i]',
        'input[id*="Login" i]',
        'input[placeholder*="Login" i]',
      ];
      const passSelectors = [
        'input[name="password"]',
        'input[type="password"]',
      ];
      const submitSelectors = [
        'button[type="submit"]',
        'input[type="submit"]',
        'button:has-text("Login")',
        'button:has-text("Sign in")',
      ];

      for (const sel of loginSelectors) {
        if (await page.locator(sel).isVisible().catch(() => false)) {
          await page.locator(sel).fill(ENV.APP_USERNAME);
          break;
        }
      }
      for (const sel of passSelectors) {
        if (await page.locator(sel).isVisible().catch(() => false)) {
          await page.locator(sel).fill(ENV.APP_PASSWORD);
          break;
        }
      }
      for (const sel of submitSelectors) {
        if (await page.locator(sel).isVisible().catch(() => false)) {
          await page.locator(sel).click();
          break;
        }
      }

      await page.waitForLoadState("networkidle");

      // If BEARER_TOKEN exists, inject it into storage
      if (ENV.BEARER_TOKEN) {
        await page.evaluate((token) => {
          localStorage.setItem("token", token);
          localStorage.setItem("access_token", token);
        }, ENV.BEARER_TOKEN);
      }

    } catch (err) {
      logger.warn(`Login during reconcile had issues: ${err} — continuing`);
    }
  }

  // ═════════════════════════════════════════════════════════════
  // triggerDynamicContent
  // Some fields only appear after scroll / click / interaction
  // ═════════════════════════════════════════════════════════════
  private async triggerDynamicContent(page: Page): Promise<void> {
    try {
      // Scroll through page to trigger lazy-render
      await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
      await page.waitForTimeout(500);
      await page.evaluate(() => window.scrollTo(0, 0));

      // Click any "Show more" / "Expand" buttons
      const expandSelectors = [
        'button:has-text("Show more")',
        'button:has-text("Expand")',
        '[data-toggle="collapse"]',
        '.accordion-button',
      ];
      for (const sel of expandSelectors) {
        const btn = page.locator(sel).first();
        if (await btn.isVisible().catch(() => false)) {
          await btn.click().catch(() => {});
          await page.waitForTimeout(300);
        }
      }
    } catch {
      // Non-critical — ignore errors here
    }
  }

  // ═════════════════════════════════════════════════════════════
  // extractFields — reads actual DOM fields from live page
  // ═════════════════════════════════════════════════════════════
  private async extractFields(page: Page): Promise<LiveField[]> {
    return page.evaluate(() => {
      const EXCLUDED_TYPES = ["hidden", "submit", "reset", "button", "image", "file"];

      function getLabel(el: Element): string {
        const id = el.getAttribute("id");
        if (id) {
          const lbl = document.querySelector(`label[for="${id}"]`);
          if (lbl) return lbl.textContent?.trim() ?? "";
        }
        const ariaLabel = el.getAttribute("aria-label");
        if (ariaLabel) return ariaLabel.trim();

        const parentLabel = el.closest("label");
        if (parentLabel) return parentLabel.textContent?.trim() ?? "";

        return (el as HTMLInputElement).placeholder?.trim() ?? "";
      }

      function getSection(el: Element): string {
        const fieldset = el.closest("fieldset");
        if (fieldset) {
          return fieldset.querySelector("legend")?.textContent?.trim() ?? "fieldset";
        }
        const section = el.closest("[data-section], .form-section, .form-group, section");
        if (section) {
          return (
            section.getAttribute("data-section") ??
            section.querySelector("h2,h3,h4")?.textContent?.trim() ??
            "section"
          );
        }
        return "default";
      }

      function getSelector(el: Element): string {
        const id   = el.getAttribute("id");
        const name = el.getAttribute("name");
        if (id)   return `#${id}`;
        if (name) return `[name="${name}"]`;
        return el.tagName.toLowerCase();
      }

      function getStepIndex(el: Element): number {
        const step = el.closest("[data-step], .step, .form-step, .wizard-step");
        if (!step) return 0;
        return parseInt(step.getAttribute("data-step") ?? "1", 10) - 1;
      }

      function isVisible(el: Element): boolean {
        const htmlEl = el as HTMLElement;
        const style  = window.getComputedStyle(htmlEl);
        return (
          style.display     !== "none"    &&
          style.visibility  !== "hidden"  &&
          style.opacity     !== "0"       &&
          htmlEl.offsetParent !== null
        );
      }

      const elements = Array.from(
        document.querySelectorAll("input, select, textarea")
      );

      return elements
        .filter(el => {
          const type = (el as HTMLInputElement).type?.toLowerCase() ?? "";
          return !EXCLUDED_TYPES.includes(type) && isVisible(el);
        })
        .map(el => {
          const input = el as HTMLInputElement;
          const name  = input.name || input.id || input.placeholder || "";
          const options = el.tagName === "SELECT"
            ? Array.from((el as HTMLSelectElement).options)
                .map(o => o.text.trim())
                .filter(t => t && !t.startsWith("--") && !t.startsWith("Select"))
            : [];

          return {
            name:        name,
            id:          input.id          || "",
            type:        input.type        || el.tagName.toLowerCase(),
            label:       getLabel(el),
            placeholder: input.placeholder || "",
            required:    input.required    || el.hasAttribute("required"),
            selector:    getSelector(el),
            options,
            pattern:     input.pattern     || "",
            minLength:   input.minLength   > 0 ? input.minLength   : undefined,
            maxLength:   input.maxLength   < 524288 && input.maxLength > 0
                           ? input.maxLength : undefined,
            section:     getSection(el),
            stepIndex:   getStepIndex(el),
            visible:     true,
          };
        })
        .filter(f => f.name.length > 0); // Must have a usable name
    });
  }

  // ═════════════════════════════════════════════════════════════
  // compareFields — diffs schema fields vs live page fields
  // ═════════════════════════════════════════════════════════════
  private compareFields(
    liveFields:   LiveField[],
    schemaFields: ResolvedField[]
  ): {
    added:   LiveField[];    // on page, NOT in schema
    removed: string[];       // in schema, NOT on page
    kept:    string[];       // in both (matched)
    updated: LiveField[];    // in both but selector/type changed
  } {
    // Build lookup sets
    // Normalise field names for fuzzy matching
    const liveNameMap   = new Map(liveFields.map(f => [this.normalise(f.name), f]));
    const schemaPathMap = new Map(schemaFields.map(f => [
      this.normalise(f.name ?? f.fieldPath.split(".").pop() ?? ""), f
    ]));

    const added:   LiveField[] = [];
    const removed: string[]    = [];
    const kept:    string[]    = [];
    const updated: LiveField[] = [];

    // ── Fields on page but not in schema → ADD ─────────────────
    for (const [normName, liveField] of liveNameMap) {
      if (!schemaPathMap.has(normName)) {
        added.push(liveField);
      }
    }

    // ── Fields in schema → check if still on page ──────────────
    for (const [normName, schemaField] of schemaPathMap) {
      const liveMatch = liveNameMap.get(normName);

      if (!liveMatch) {
        // In schema but NOT on page → REMOVE
        removed.push(schemaField.fieldPath);
      } else {
        // In both → KEEP
        // But check if selector or type changed → UPDATE
        const selectorChanged = liveMatch.selector !== schemaField.selector;
        const typeChanged     = this.mapHtmlType(liveMatch.type) !== schemaField.type;

        if (selectorChanged || typeChanged) {
          updated.push(liveMatch);
        } else {
          kept.push(schemaField.fieldPath);
        }
      }
    }

    return { added, removed, kept, updated };
  }

  // ═════════════════════════════════════════════════════════════
  // buildReconciledSchema
  // Produces a new FieldSchema that exactly matches the live page
  // ═════════════════════════════════════════════════════════════
  private buildReconciledSchema(
    currentSchema: FieldSchema,
    liveFields:    LiveField[],
    schemaFields:  ResolvedField[],
    added:         LiveField[],
    removed:       string[],
    updated:       LiveField[]
  ): FieldSchema {

    // If nothing changed — return original schema unchanged
    if (added.length === 0 && removed.length === 0 && updated.length === 0) {
      logger.info("✅ Schema already matches live page — no changes needed");
      return currentSchema;
    }

    // Group live fields by section — this becomes the new structure
    const sectionMap = new Map<string, LiveField[]>();

    for (const lf of liveFields) {
      const key = lf.section || "default";
      if (!sectionMap.has(key)) sectionMap.set(key, []);
      sectionMap.get(key)!.push(lf);
    }

    // Build new sections from live page structure
    const newSections: Section[] = Array.from(sectionMap.entries()).map(
      ([sectionName, fields]) => {

        // Section is mandatory if ANY field in it is required
        const hasMandatory = fields.some(f => f.required);

        return {
          sectionName,
          mandatory: hasMandatory,
          weight:    hasMandatory ? 10 : 5,
          label:     this.toLabel(sectionName),
          stepIndex: fields[0]?.stepIndex ?? 0,
          fields:    fields.map(lf => this.liveFieldToSchemaField(lf, currentSchema, schemaFields)),
        };
      }
    );

    // Rebuild schema preserving original metadata
    const reconciled: FieldSchema = {
      ...currentSchema,
      schemaId:  `${currentSchema.schemaId}-reconciled`,
      sections:  newSections,
      // Preserve goal condition, astarConfig, endpoint, method
    };

    logger.info(`  Reconciled schema: ${newSections.length} sections, ${liveFields.length} fields`);
    return reconciled;
  }

  // ═════════════════════════════════════════════════════════════
  // liveFieldToSchemaField
  // Converts a LiveField into a FieldSchema Field object
  // Tries to PRESERVE existing schema metadata (dataHints, validationRule)
  // if the field already exists in the original schema
  // ═════════════════════════════════════════════════════════════
  private liveFieldToSchemaField(
    lf:           LiveField,
    origSchema:   FieldSchema,
    schemaFields: ResolvedField[]
  ): Field {

    // Try to find matching field in original schema → preserve its metadata
    const normName    = this.normalise(lf.name);
    const existing    = schemaFields.find(
      sf => this.normalise(sf.name ?? sf.fieldPath.split(".").pop() ?? "") === normName
    );

    const fieldType = this.mapHtmlType(lf.type) as Field["type"];

    return {
      name:     lf.name,
      type:     fieldType,
      weight:   lf.required ? 9 : 4,
      label:    lf.label    || this.toLabel(lf.name),
      selector: lf.selector,
      placeholder: lf.placeholder || undefined,

      // Preserve dropdown options from live scan
      validValues: lf.options.length > 0 ? lf.options : undefined,

      // Preserve validation rules from original schema if field matched
      // Otherwise infer from live HTML attributes
      validationRule: existing?.validationRule ?? (
        lf.pattern || lf.minLength || lf.maxLength
          ? {
              pattern:   lf.pattern   || undefined,
              minLength: lf.minLength || undefined,
              maxLength: lf.maxLength || undefined,
            }
          : undefined
      ),

      // Preserve dataHints (test data) from original schema if matched
      // This is the MOST valuable thing to preserve — human-curated test data
      dataHints: existing?.dataHints ?? this.inferDataHints(lf),

      // Preserve API key mapping if existed
      apiKey: existing?.apiKey ?? undefined,
    };
  }

  // ═════════════════════════════════════════════════════════════
  // inferDataHints — smart default test data for new fields
  // ═════════════════════════════════════════════════════════════
  private inferDataHints(lf: LiveField): Field["dataHints"] {
    const name = lf.name.toLowerCase();
    const type = lf.type.toLowerCase();

    // Dropdown — use the options themselves as valid samples
    if (lf.options.length > 0) {
      return {
        validSamples:   lf.options.slice(0, 3),
        invalidSamples: ["INVALID_OPTION_9999"],
      };
    }

    // Type-based inference
    if (type === "email" || name.includes("email")) {
      return {
        validSamples:   ["test@astra.com", "qa@example.com"],
        invalidSamples: ["notanemail", "missing@"],
        format:         "email",
      };
    }
    if (type === "tel" || name.includes("phone") || name.includes("mobile")) {
      return {
        validSamples:   ["9876543210", "8123456789"],
        invalidSamples: ["12345", "abcdefghij"],
      };
    }
    if (type === "password" || name.includes("password")) {
      return {
        validSamples:   ["Test@1234", "Secure#Pass9"],
        invalidSamples: ["weak", "12345678"],
      };
    }
    if (type === "date" || name.includes("date")) {
      return {
        validSamples:   ["2024-01-15", "2025-06-01"],
        invalidSamples: ["32-13-2000", "notadate"],
        format:         "YYYY-MM-DD",
      };
    }
    if (type === "number" || name.includes("amount") || name.includes("budget")) {
      return {
        validSamples:   ["100", "5000", "25000"],
        invalidSamples: ["-1", "abc", "0"],
      };
    }
    if (type === "url" || name.includes("url") || name.includes("website")) {
      return {
        validSamples:   ["https://example.com", "https://test.astra.io"],
        invalidSamples: ["not-a-url", "ftp//broken"],
      };
    }
    if (name.includes("name")) {
      return {
        validSamples:   ["Test Campaign", "ASTRA Auto Test", "QA Validation Run"],
        invalidSamples: ["", "A"],
      };
    }

    // Generic fallback
    return {
      validSamples:   [`test_${lf.name}_value`, `astra_${lf.name}`],
      invalidSamples: ["", " "],
    };
  }

  // ═════════════════════════════════════════════════════════════
  // saveReconciledSchema — persists the reconciled schema as JSON
  // ═════════════════════════════════════════════════════════════
  private async saveReconciledSchema(schema: FieldSchema): Promise<void> {
    await fs.ensureDir(path.dirname(this.schemaPath));
    await fs.writeJson(this.schemaPath, schema, { spaces: 2 });
    logger.info(`💾 Reconciled schema saved → ${this.schemaPath}`);
  }

  // ═════════════════════════════════════════════════════════════
  // logDiff — logs what changed in a clear readable format
  // ═════════════════════════════════════════════════════════════
  private logDiff(
    added:   LiveField[],
    removed: string[],
    kept:    string[],
    updated: LiveField[]
  ): void {
    logger.divider("Schema Reconciliation Diff");

    if (kept.length > 0) {
      logger.info(`✅ KEPT    (${kept.length}): ${kept.join(", ")}`);
    }
    if (added.length > 0) {
      logger.info(`➕ ADDED   (${added.length}): ${added.map(f => f.name).join(", ")}`);
      logger.warn("   → These fields were on the page but missing from schema");
    }
    if (removed.length > 0) {
      logger.info(`➖ REMOVED (${removed.length}): ${removed.join(", ")}`);
      logger.warn("   → These fields were in schema but NOT found on page");
    }
    if (updated.length > 0) {
      logger.info(`🔄 UPDATED (${updated.length}): ${updated.map(f => f.name).join(", ")}`);
      logger.info("   → Selector or type refreshed from live page");
    }
    if (added.length === 0 && removed.length === 0 && updated.length === 0) {
      logger.info("🎯 PERFECT MATCH — schema already matches live page exactly");
    }
  }

  // ═════════════════════════════════════════════════════════════
  // Utilities
  // ═════════════════════════════════════════════════════════════

  // normalise — removes case, spaces, underscores for fuzzy match
  // "firstName" === "first_name" === "First Name" === "firstname"
  private normalise(name: string): string {
    return name
      .toLowerCase()
      .replace(/[\s_\-\.]/g, "")  // remove spaces, _, -, .
      .replace(/([a-z])([A-Z])/g, "$1$2"); // keep camelCase as-is after lower
  }

  // mapHtmlType — maps raw HTML input type → ASTRA FieldType
  private mapHtmlType(htmlType: string): string {
    const typeMap: Record<string, string> = {
      "text":     "text",
      "email":    "email",
      "password": "password",
      "tel":      "phone",
      "number":   "number",
      "date":     "date",
      "checkbox": "checkbox",
      "radio":    "radio",
      "select":   "dropdown",
      "select-one": "dropdown",
      "select-multiple": "dropdown",
      "textarea": "textarea",
      "url":      "url",
      "file":     "file",
    };
    return typeMap[htmlType.toLowerCase()] ?? "text";
  }

  // toLabel — converts camelCase/snake_case to "Human Readable Label"
  private toLabel(name: string): string {
    return name
      .replace(/([A-Z])/g, " $1")
      .replace(/[_\-]/g, " ")
      .replace(/\b\w/g, c => c.toUpperCase())
      .trim();
  }

  // buildReport — assembles the ReconcileReport
  private buildReport(
    added:     LiveField[],
    removed:   string[],
    kept:      string[],
    updated:   LiveField[],
    allSchema: string[],
    totalLive: number,
    totalSchema: number,
    duration:  number
  ): ReconcileReport {
    return {
      totalLiveFields:   totalLive,
      totalSchemaFields: totalSchema,
      fieldsAdded:       added.map(f => f.name),
      fieldsRemoved:     removed,
      fieldsKept:        kept,
      fieldsUpdated:     updated.map(f => f.name),
      reconciled:        added.length > 0 || removed.length > 0 || updated.length > 0,
      savedTo:           this.schemaPath,
      duration,
    };
  }
}

// ═══════════════════════════════════════════════════════════════
// reconcileUiSchema — convenience wrapper for runners
// ═══════════════════════════════════════════════════════════════
export async function reconcileUiSchema(
  schema: FieldSchema
): Promise<{ schema: FieldSchema; report: ReconcileReport }> {
  const reconciler = new SchemaReconciler("ui");
  return reconciler.reconcile(schema);
}

// ═══════════════════════════════════════════════════════════════
// reconcileApiSchema — convenience wrapper for API runner
// ═══════════════════════════════════════════════════════════════
export async function reconcileApiSchema(
  schema: FieldSchema
): Promise<{ schema: FieldSchema; report: ReconcileReport }> {
  const reconciler = new SchemaReconciler("api");
  return reconciler.reconcile(schema);
}