// ═══════════════════════════════════════════════════════════════
// runners/api/apiTestRunner.ts
// ASTRA Framework — API Test Runner
// Orchestrates: schema load → blueprint load → A* codegen → exec
// ═══════════════════════════════════════════════════════════════

import * as fs       from "fs-extra";
import * as path     from "path";
import { execSync }  from "child_process";
import { ENV }       from "../../utils/envLoader";
import { logger }    from "../../utils/logger";
import { ApiCodeGenerator }  from "../../codegen/apiCodeGenerator";
import { FieldSchema }       from "../../schemas/fieldSchema.interface";
import { ApiBlueprint }      from "../../preflight/networkInterceptorAnalyser";
import { loadApiSchema }     from "../../utils/schemaResolver";
import { reconcileApiSchema } from "../../utils/schemaReconciler";

// ═══════════════════════════════════════════════════════════════
// Interfaces
// ═══════════════════════════════════════════════════════════════
export interface ApiRunResult {
  success:        boolean;
  testsGenerated: number;
  testsPassed:    number;
  testsFailed:    number;
  endpointsCovered: number;
  duration:       number;
  reportPath:     string;
}

// ═══════════════════════════════════════════════════════════════
// ApiTestRunner
// ═══════════════════════════════════════════════════════════════
export class ApiTestRunner {

  private readonly schemaPath:    string;
  private readonly blueprintPath: string;
  private readonly reportDir:     string;

  constructor(schemaPath?: string, blueprintPath?: string) {
    this.schemaPath    = schemaPath
      ?? path.resolve(__dirname, "../../schemas/api/autoGeneratedSchema.json");
    this.blueprintPath = blueprintPath
      ?? path.resolve(__dirname, "../../payloads/requests/apiBlueprint.json");
    this.reportDir     = path.resolve(__dirname, "../../", ENV.TEST_REPORT_DIR);
  }

  // ═══════════════════════════════════════════════════════════
  // run — full pipeline: load → generate → execute
  // ═══════════════════════════════════════════════════════════
  async run(): Promise<ApiRunResult> {
    const startTime = Date.now();
    logger.divider("API Test Runner — Starting");

    // ─── Validate Bearer token ────────────────────────────────
    if (!ENV.BEARER_TOKEN) {
      logger.warn("⚠️  BEARER_TOKEN is empty — API tests may return 401");
      logger.warn("   Run preflight to auto-populate: npm run preflight");
    }

    // ─── Load schema ──────────────────────────────────────────
    const rawSchema = await this.loadSchema();
    if (!rawSchema) {
      return this.failResult("API schema not found", startTime);
    }

    // ─── Reconcile schema against live page ───────────────────
    logger.info("🔄 Reconciling API schema against live page...");
    const { schema, report } = await reconcileApiSchema(rawSchema);

    if (report.reconciled) {
      logger.info(`  Schema updated: +${report.fieldsAdded.length} added, -${report.fieldsRemoved.length} removed`);
    } else {
      logger.info("  Schema matches live page ✅");
    }

    // ─── Load API blueprint ───────────────────────────────────
    const blueprints = await this.loadBlueprints();
    logger.info(`Blueprint loaded: ${blueprints.length} endpoints`);

    // ─── Generate API test files ──────────────────────────────
    logger.info("⚙️  Generating API test files from A* search...");
    const generator = new ApiCodeGenerator(schema, blueprints);
    const codeGen   = await generator.generate();

    logger.info(`✅ Generated ${codeGen.savedTo.length} API test files`);

    // ─── Execute generated tests ──────────────────────────────
    logger.info("🚀 Executing generated Playwright API tests...");
    const execResult = this.executeTests(codeGen.savedTo);

    const duration = Date.now() - startTime;

    // ─── Count unique endpoints ───────────────────────────────
    const endpointsCovered = blueprints.length > 0
      ? new Set(blueprints.map((b) => b.path)).size
      : 1;

    return {
      success:          execResult.exitCode === 0,
      testsGenerated:   codeGen.savedTo.length,
      testsPassed:      execResult.passed,
      testsFailed:      execResult.failed,
      endpointsCovered,
      duration,
      reportPath:       path.join(this.reportDir, "index.html"),
    };
  }

  // ═══════════════════════════════════════════════════════════
  // runEndpoint — run tests for a specific endpoint only
  // ═══════════════════════════════════════════════════════════
  async runEndpoint(method: string, endpointPath: string): Promise<ApiRunResult> {
    const startTime = Date.now();
    logger.divider(`API Runner — ${method} ${endpointPath}`);

    const schema     = await this.loadSchema();
    const blueprints = await this.loadBlueprints();

    if (!schema) return this.failResult("Schema not found", startTime);

    // ─── Filter blueprint to specific endpoint ────────────────
    const filtered = blueprints.filter(
      (b) =>
        b.method.toUpperCase() === method.toUpperCase() &&
        b.path === endpointPath
    );

    if (filtered.length === 0) {
      logger.warn(`No blueprint found for ${method} ${endpointPath} — using defaults`);
    }

    const generator  = new ApiCodeGenerator(schema, filtered);
    const codeGen    = await generator.generate();
    const execResult = this.executeTests(codeGen.savedTo);

    return {
      success:          execResult.exitCode === 0,
      testsGenerated:   codeGen.savedTo.length,
      testsPassed:      execResult.passed,
      testsFailed:      execResult.failed,
      endpointsCovered: 1,
      duration:         Date.now() - startTime,
      reportPath:       path.join(this.reportDir, "index.html"),
    };
  }

  // ═══════════════════════════════════════════════════════════
  // loadSchema — delegates to central schemaResolver
  // Priority: autoGeneratedSchema.json → registrationSchema.ts → default
  // ═══════════════════════════════════════════════════════════
  private async loadSchema(): Promise<FieldSchema | null> {
    try {
      return await loadApiSchema();
    } catch (err) {
      logger.error(`Schema load failed: ${err}`);
      return null;
    }
  }

  // ═══════════════════════════════════════════════════════════
  // loadBlueprints
  // ═══════════════════════════════════════════════════════════
  private async loadBlueprints(): Promise<ApiBlueprint[]> {
    if (!await fs.pathExists(this.blueprintPath)) {
      logger.warn(`API blueprint not found: ${this.blueprintPath}`);
      logger.warn("Network interceptor may not have captured endpoints");
      return [];
    }
    return await fs.readJson(this.blueprintPath);
  }

  // ═══════════════════════════════════════════════════════════
  // executeTests — runs Playwright CLI on generated API specs
  // ═══════════════════════════════════════════════════════════
  private executeTests(
    specFiles: string[]
  ): { exitCode: number; passed: number; failed: number } {
    fs.ensureDirSync(this.reportDir);

    const specPaths = specFiles.map((f) => `"${f}"`).join(" ");

    // API tests don't need a browser project — use chromium as default
    const playwrightCmd = [
      "npx playwright test",
      specPaths,
      `--project=${ENV.BROWSER}`,
      "--reporter=html,list",
      `--output="${this.reportDir}/api-artifacts"`,
    ].join(" ");

    logger.info(`Running: ${playwrightCmd}`);

    try {
      execSync(playwrightCmd, {
        stdio:   "inherit",
        cwd:     path.resolve(__dirname, "../../"),
        env:     {
          ...process.env,
          // Ensure latest token is passed to test process
          BEARER_TOKEN: ENV.BEARER_TOKEN,
          API_BASE_URL: ENV.API_BASE_URL || ENV.BASE_URL,
        },
        timeout: ENV.API_TIMEOUT * 20,
      });

      logger.info("✅ API tests completed successfully");
      return { exitCode: 0, passed: specFiles.length, failed: 0 };

    } catch (error: any) {
      const exitCode = error.status ?? 1;
      logger.error(`API tests completed with failures — exit code: ${exitCode}`);
      return { exitCode, passed: 0, failed: specFiles.length };
    }
  }

  // ═══════════════════════════════════════════════════════════
  // failResult
  // ═══════════════════════════════════════════════════════════
  private failResult(reason: string, startTime: number): ApiRunResult {
    logger.error(`API Runner failed: ${reason}`);
    return {
      success:          false,
      testsGenerated:   0,
      testsPassed:      0,
      testsFailed:      0,
      endpointsCovered: 0,
      duration:         Date.now() - startTime,
      reportPath:       "",
    };
  }
}

// ═══════════════════════════════════════════════════════════════
// Direct execution: npm run test:api
// ═══════════════════════════════════════════════════════════════
async function main(): Promise<void> {
  logger.divider("ASTRA — API Test Runner");

  const runner = new ApiTestRunner();
  const result = await runner.run();

  logger.divider("API Test Runner — Results");
  logger.info(`  Success           : ${result.success ? "✅ YES" : "❌ NO"}`);
  logger.info(`  Tests Generated   : ${result.testsGenerated}`);
  logger.info(`  Tests Passed      : ${result.testsPassed}`);
  logger.info(`  Tests Failed      : ${result.testsFailed}`);
  logger.info(`  Endpoints Covered : ${result.endpointsCovered}`);
  logger.info(`  Duration          : ${result.duration}ms`);
  logger.info(`  Report            : ${result.reportPath}`);

  process.exit(result.success ? 0 : 1);
}

if (require.main === module) {
  main().catch((err) => {
    logger.error(`API runner crashed: ${err}`);
    process.exit(1);
  });
}